name: 🚀 Release
on:
  push:
    tags: [v*]
jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1
    - name: Install Release Dependencies
      run: cpanm -qn Module::Build CPAN::Uploader

    # CPAN
    - name: Package the Release
      id: package
      run: perl Build.PL && ./Build manifest && ./Build dist && echo "tarball=$(./Build tarball_name)" >> $GITHUB_OUTPUT
    - name: Generate Release Changes
      run: ./Build latest_changes
    - name: Release on CPAN
      env:
        CPANPASS: ${{ secrets.CPAN_PASSWORD }}
        CPANUSER: ${{ secrets.CPAN_USERNAME }}
      run: cpan-upload --user "$CPANUSER" --password "$CPANPASS" '${{ steps.package.outputs.tarball }}'

    # GitHub
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Release ${{ github.ref }}"
        body_path: latest-changes.md
        files: ${{ steps.package.outputs.tarball }}
